// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAK8zyfx6jVu_7sF5nVIZ1G1QOKFADxI8',
    appId: '1:662241768792:web:04689822ab4f9de7d1212d',
    messagingSenderId: '662241768792',
    projectId: 'e-commerce-e784a',
    authDomain: 'e-commerce-e784a.firebaseapp.com',
    storageBucket: 'e-commerce-e784a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDakR5j17OPBuRQxjeqUis5CmqI2kwMp8E',
    appId: '1:662241768792:android:adc7d308d6f75180d1212d',
    messagingSenderId: '662241768792',
    projectId: 'e-commerce-e784a',
    storageBucket: 'e-commerce-e784a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCggJFUVRam6AN75t_HJAcfrw3-lt9Seiw',
    appId: '1:662241768792:ios:79d2388075bc7bcbd1212d',
    messagingSenderId: '662241768792',
    projectId: 'e-commerce-e784a',
    storageBucket: 'e-commerce-e784a.firebasestorage.app',
    iosBundleId: 'com.domain.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCggJFUVRam6AN75t_HJAcfrw3-lt9Seiw',
    appId: '1:662241768792:ios:79d2388075bc7bcbd1212d',
    messagingSenderId: '662241768792',
    projectId: 'e-commerce-e784a',
    storageBucket: 'e-commerce-e784a.firebasestorage.app',
    iosBundleId: 'com.domain.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAK8zyfx6jVu_7sF5nVIZ1G1QOKFADxI8',
    appId: '1:662241768792:web:efe5a706692a5d22d1212d',
    messagingSenderId: '662241768792',
    projectId: 'e-commerce-e784a',
    authDomain: 'e-commerce-e784a.firebaseapp.com',
    storageBucket: 'e-commerce-e784a.firebasestorage.app',
  );
}
